---
- name: Update and Upgrade Ubuntu Desktop
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Install essential packages
      apt:
        name:
          - git
          - p7zip-full
          - curl
          - wget
          - vim
          - htop
          - build-essential
          - net-tools
          - tree
          - unzip
          - tmux
          - apt-transport-https
          - yasm
          - nasm
          - valgrind
          - gdb 
          - cmake
          - automake
          - llvm
          - clang
        state: present

    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Notify if reboot is required
      debug:
        msg: "System reboot is required!"
      when: reboot_required.stat.exists